version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4:4.26
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: root@pgadmin
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 8000:80
